import type { BackgroundColors, BrandColors, ColorsInterface, ElementColors, FeedbackColors, GrayScaleColors, InteractionColors } from '../types/color.types';
export declare const defaultDarkLegacyColors: {
    colorOne: string;
    colorTwo: string;
    colorThree: string;
    colorFour: string;
    colorFive: string;
    primary: string;
    primaryLighter: string;
    secondary: string;
    accent: string;
    accentLighter: string;
    accent50: string;
    accent80: string;
    tertiary: string;
    outline: string;
    shadow: string;
    secondaryButtonBackgroundColor: string;
    backdrop: string;
    background: string;
    headerBackground: string;
    surface: string;
    surfaceVariant: string;
    error: string;
    warningAlpha22: string;
    warningAlpha62: string;
    errorContainer: string;
    onError: string;
    onErrorContainer: string;
    placeholder: string;
    selectedColorOne10: string;
    selectedColorOne40: string;
    selectedColorOne100: string;
    accentDarkest: string;
    primaryDarkest: string;
    onPrimary: string;
    onPrimaryContainer: string;
    onSecondary: string;
    onSecondaryContainer: string;
    onSurface: string;
    onSurfaceVariant: string;
    onSurfaceDisabled: string;
    onBackground: string;
};
export declare const defaultDarkGrayScaleColors: GrayScaleColors;
export declare const defaultDarkBrandColors: BrandColors;
export declare const defaultDarkBackgroundColors: BackgroundColors;
export declare const defaultDarkElementColors: ElementColors;
export declare const defaultDarkFeedbackColors: FeedbackColors;
export declare const defaultDarkInteractionColors: InteractionColors;
export declare const darkColors: ColorsInterface;
