npmPublishAccess: restricted

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "$NPM_PUBLISH_TOKEN"  # placeholder for the publish token

npmScopes:
  your-scope:  # replace 'your-scope' with your actual scope name
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "$NPM_READ_TOKEN"  # placeholder for the read token

# ... rest of your .yarnrc.yml settings ...
