nodeLinker: node-modules

npmPublishAccess: public

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: $NPM_PUBLISH_TOKEN

npmScopes:
  devlander:  # Use your actual package scope here
    npmAuthToken: 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
    npmRegistryServer: "https://registry.npmjs.org"
