export * from './utils/calculate-percentage-by-part-and-whole'
export * from './types/base-button.props.interface'
export * from './types/svg-props.interface'
export * from "./types/font-type.enum"
export * from "./types/theme.types"
export * from "./types/custom-style-props.interface"
export * from "./types/text.types"

export * from "./utils/has-letter"
export * from "./utils/slice-into-chunks"
export * from "./utils/video-timestamp-to-seconds"
export * from "./types/fixed-array.type"
export * from "./types/font-weight.types"
export * from "./types/text-style.props"
export * from "./defaults/text-inputs.defaults"
export * from "./types/base-header.props"
export * from "./types/base-image.interface"
export * from "./types/base-view.interface"
export * from "./types/base-theme.interface"
export * from "./types/base-scrollview.interface"
export * from "./utils/get-style/cap-font-size"
export {paddingObj, paddingForScrollView, paddingForScrollViewTwo} from "./utils/get-style/constant-units-for-theme"
export * from "./utils/get-style/get-line-height"
export * from "./utils/get-style/get-style-for-container-props"
export * from "./utils/get-style/get-style-for-touchable-opacity-props"
export * from "./utils/get-style/handle-box-shadows"
export * from "./utils/get-style/handle-color-from-theme"
export * from "./utils/get-style/handle-font-for-theme"
export * from "./utils/get-style/handle-font-size-props"

