name: Yarn Install and Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Load .env file
        run: |
          export $(cat .env | xargs)

      - name: Set Environment Variables with fallback to .env
        run: |
          echo "NPM_READ_TOKEN=${{ secrets.NPM_READ_TOKEN || env.NPM_READ_TOKEN }}" >> $GITHUB_ENV
          echo "NPM_PUBLISH_TOKEN=${{ secrets.NPM_PUBLISH_TOKEN || env.NPM_PUBLISH_TOKEN }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Check and bump version if needed
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          CURRENT_VERSION=$(npm view $PACKAGE_NAME version)
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          if [ "$CURRENT_VERSION" == "$LOCAL_VERSION" ]; then
            npm version patch
          fi

      - name: Publish to npm
        run: npm publish
